server:
  port: 8100

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  db_name: ${DATABASE_DB_NAME}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB:0}

auth:
  password_secret: ${PASSWORD_SECRET}
  access_secret: ${ACCESS_SECRET}
  refresh_secret: ${REFEESH_SECRET}
