root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -mod=mod -o ./tmp/main ./cmd/main.go"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "external/proto", "docs", ".git", "scripts"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*\\.pb\\.go$", ".*\\.md$"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 1000
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false