// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicProfileByIds = `-- name: GetPublicProfileByIds :many
SELECT id, first_name, last_name FROM users
WHERE id = ANY($1::string[])
`

type GetPublicProfileByIdsRow struct {
	ID        pgtype.UUID
	FirstName string
	LastName  string
}

func (q *Queries) GetPublicProfileByIds(ctx context.Context, userIds []string) ([]GetPublicProfileByIdsRow, error) {
	rows, err := q.db.Query(ctx, getPublicProfileByIds, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicProfileByIdsRow
	for rows.Next() {
		var i GetPublicProfileByIdsRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, phone, password, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, phone, password, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
  first_name,
  last_name,
  email,
  phone,
  password,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, first_name, last_name, email, phone, password, created_at, updated_at
`

type InsertUserParams struct {
	FirstName string
	LastName  string
	Email     string
	Phone     pgtype.Text
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users
SET
  first_name = $2,
  last_name = $3,
  email = $4,
  phone = $5,
  updated_at = $6
WHERE id = $1
`

type UpdateUserParams struct {
	ID        pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.UpdatedAt,
	)
}

const updateUserPassword = `-- name: UpdateUserPassword :execresult
UPDATE users
SET
  password = $2,
  updated_at = $3
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID        pgtype.UUID
	Password  string
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password, arg.UpdatedAt)
}
